#!/bin/bash
BESTAND=$1
gnuplot <<- EOF
set terminal png size 1024,768
set output '$BESTAND-percent.png'
set style fill solid 0.5
set style data boxes
set yrange [0:40]
#plot "$BESTAND" using 1:2 with lines
plot "$BESTAND" using 2:6

set output '$BESTAND-opening.png'
set style fill solid 0.5
set style data boxes
unset yrange
plot "$BESTAND" using 2:10
EOF
