#!/bin/bash
BESTAND=$1
gnuplot <<- EOF
set terminal png size 1024,768
set output '$BESTAND-percent.png'
set style fill solid 0.5
set style data boxes
set yrange [0:40]
set xlabel "Hours"
set ylabel "Percent"
#plot "$BESTAND" using 1:2 with lines
plot "$BESTAND" using 2:6 linecolor rgb '#0072bd'

set output '$BESTAND-opening.png'
set style fill solid 0.5
set style data boxes
unset yrange
set xlabel "Hours"
set ylabel "Number of openings"
plot "$BESTAND" using 2:10 linecolor rgb '#4dbeee'

set output '$BESTAND-avgopen.png'
set style fill solid 0.5
set style data boxes
unset yrange
set xlabel "Hours"
set ylabel "Avg open time"
plot "$BESTAND" using 2:14 linecolor rgb '#77ac30'
EOF
